### ISSUE TITLE
Change a Heading in README

### ISSUE THREAD

**Issue by clairecharles** [Anugrahsr/Awesome-web3-Security#11]
## Description
In the readme, there is a section with a list of web3 resources with the heading 'RoadMap'
![Screenshot 2023-01-03 at 11 21 21](https://user-images.githubusercontent.com/67120042/210339428-46bb0145-3944-41b0-bab8-c48f1dff2036.png)

## Solution
Change the heading to 'Resources To Learn Solidity'

**Comment by Anugrahsr** [comment]
Ok! fixed it👍
